### ISSUE TITLE
Frontend recieves 404 in AWS Amplify

### ISSUE THREAD

**Issue by nmauro2017** [nalkhish/cheap-low-traffic-stack#1]
Hello, I am able to deploy the frontend and backend locally and everything works as expected. I also completed the entire tutorial and was able to successfully deploy the backend and frontend in AWS. My AWS Amplify deployment succeeds, but when I open the link, there is no content and in the developer console I see that I am getting a 404 error from Cloudfront. Any idea why this might be happening? I've searched the internet and tried a few fixes but nothing works. Thank you!

**Comment by nalkhish** [comment]
@nmauro2017 It's great that the build and deploy steps succeed. From my understanding, the deployment pipeline is build -> deploy -> Amplify-generated url. If it's working up until the deploy step and not the Amplify-generated url, then something has to be breaking before url generation, but all that is abstracted away by AWS Amplify.

Using a custom url (Amplify-generated url -> custom url) is another story. Is that what you meant?

**Comment by nmauro2017** [comment]
Hey thanks for the quick reply! Let me clarify, it is succeeding all of build -> deploy -> Amplify-generated URL. I get the URL and can navigate to it but the page is a black screen and in the console I get the following response: 
```
Status: 404
Version: HTTP/2
Transferred: 337 B (0 B size)
Request Priority: Highest
DNS Resolution: DNS over HTTPS
```

```
HTTP/2 404 
content-length: 0
date: Fri, 21 Jun 2024 00:14:10 GMT
server: AmazonS3
x-cache: Error from cloudfront
via: 1.1 30d9e3a4b27e43a0df1da02819d5efec.cloudfront.net (CloudFront)
x-amz-cf-pop: ORD58-P3
alt-svc: h3=":443"; ma=86400
x-amz-cf-id: 6rJbVrBPue_3THiiS5GTmLpumd9RQgVhg3SdNwBel5fAsyUhqn62dQ==
X-Firefox-Spdy: h2
```

I did not change anything from the tutorial

**Comment by nalkhish** [comment]
@nmauro2017 

Yeah np

I now cloned this repository onto this new repository: [repository](https://github.com/nalkhish/cheap-clone) 

I then went to deploy it via AWS Amplify. I noticed their interface changed a bit.

One noteworthy step is I selected that the app was a monorepo and that the source in the frontend. It seems to have detected the Next.js framework:

<img width="1723" alt="image" src="https://github.com/nalkhish/cheap-low-traffic-stack/assets/43485534/e1586c42-5967-4fc2-8c20-cfb0f02c4423">

After that, it seems to succeed in deployment and becomes available:

https://main.d2wzge8u6n98dm.amplifyapp.com/

I'm going to keep the deployment up for tonight to help you debug

**Comment by nmauro2017** [comment]
Its working now! I deleted my old app and created a new one with the same exact repo using the settings you mentioned. Its just weird because I did edit the previous app's amplify build file to mark the frontend directory as the app root, but clearly something I did was wrong. Anyway, thanks again!

**Comment by nalkhish** [comment]
Nice! Glad to help.

Enjoy the low AWS bill!
